[grid]
rows = [
  ["1", "2", "3", "4", "5"],
  ["Q", "W", "E", "R", "T"],
  ["A", "S", "D", "F", "G"],
  ["Y", "X", "C", "V", "B"],
]

[keys]
h = 'left'
j = 'down'
k = 'up'
l = 'right'
return = 'confirm'
escape = 'cancel'
x = 'close-all'
shift-h = 'move-left'
shift-j = 'move-down'
shift-k = 'move-up'
shift-l = 'move-right'

[keys.workspaces]
1 = '1'
2 = '2'
3 = '3'
4 = '4'
5 = '5'
q = 'Q'
w = 'W'
e = 'E'
r = 'R'
t = 'T'
a = 'A'
s = 'S'
d = 'D'
f = 'F'
g = 'G'
y = 'Y'
x = 'X'
c = 'C'
v = 'V'


[behavior]
wrap = false
confirm_close_all = true
move_mode = "directional"
monitor_wrap = false
